from __future__ import annotations

from typing import Mapping


OMOP_SCHEMAS: Mapping[str, Mapping[str, str]] = {
    # Core OMOP clinical tables used by most criteria builders.
    "person": {
        "person_id": "int64",
        "gender_concept_id": "int64",
        "year_of_birth": "int64",
        "month_of_birth": "int64",
        "day_of_birth": "int64",
        "race_concept_id": "int64",
        "ethnicity_concept_id": "int64",
    },
    "observation_period": {
        "observation_period_id": "int64",
        "person_id": "int64",
        "observation_period_start_date": "date",
        "observation_period_end_date": "date",
        "period_type_concept_id": "int64",
    },
    "visit_occurrence": {
        "visit_occurrence_id": "int64",
        "person_id": "int64",
        "visit_concept_id": "int64",
        "visit_start_date": "date",
        "visit_end_date": "date",
        "visit_type_concept_id": "int64",
        "visit_source_concept_id": "int64",
    },
    "condition_occurrence": {
        "condition_occurrence_id": "int64",
        "person_id": "int64",
        "condition_concept_id": "int64",
        "condition_start_date": "date",
        "condition_end_date": "date",
        "condition_type_concept_id": "int64",
        "condition_status_concept_id": "int64",
        "condition_source_concept_id": "int64",
        "visit_occurrence_id": "int64",
    },
    "measurement": {
        "measurement_id": "int64",
        "person_id": "int64",
        "measurement_concept_id": "int64",
        "measurement_date": "date",
        "measurement_datetime": "timestamp",
        "measurement_type_concept_id": "int64",
        "operator_concept_id": "int64",
        "value_as_number": "float64",
        "value_as_concept_id": "int64",
        "unit_concept_id": "int64",
        "range_low": "float64",
        "range_high": "float64",
        "visit_occurrence_id": "int64",
        "measurement_source_concept_id": "int64",
    },
    "drug_exposure": {
        "drug_exposure_id": "int64",
        "person_id": "int64",
        "drug_concept_id": "int64",
        "drug_exposure_start_date": "date",
        "drug_exposure_end_date": "date",
        "days_supply": "int64",
        "drug_type_concept_id": "int64",
        "drug_source_concept_id": "int64",
        "visit_occurrence_id": "int64",
    },
    "procedure_occurrence": {
        "procedure_occurrence_id": "int64",
        "person_id": "int64",
        "procedure_concept_id": "int64",
        "procedure_date": "date",
        "procedure_end_date": "date",
        "procedure_type_concept_id": "int64",
        "procedure_source_concept_id": "int64",
        "visit_occurrence_id": "int64",
    },
    "device_exposure": {
        "device_exposure_id": "int64",
        "person_id": "int64",
        "device_concept_id": "int64",
        "device_exposure_start_date": "date",
        "device_exposure_end_date": "date",
        "device_type_concept_id": "int64",
        "device_source_concept_id": "int64",
        "visit_occurrence_id": "int64",
    },
    "observation": {
        "observation_id": "int64",
        "person_id": "int64",
        "observation_concept_id": "int64",
        "observation_date": "date",
        "value_as_number": "float64",
        "value_as_concept_id": "int64",
        "unit_concept_id": "int64",
        "observation_type_concept_id": "int64",
        "visit_occurrence_id": "int64",
    },
    "death": {
        "person_id": "int64",
        "death_date": "date",
        "death_type_concept_id": "int64",
    },
    "specimen": {
        "specimen_id": "int64",
        "person_id": "int64",
        "specimen_concept_id": "int64",
        "specimen_date": "date",
        "specimen_type_concept_id": "int64",
        "visit_occurrence_id": "int64",
    },
    # Support tables referenced by optional filters. Keep empty unless needed.
    "provider": {"provider_id": "int64", "specialty_concept_id": "int64"},
    "care_site": {"care_site_id": "int64", "place_of_service_concept_id": "int64"},
    "location_history": {
        "location_history_id": "int64",
        "entity_id": "int64",
        "domain_id": "string",
        "location_id": "int64",
        "start_date": "timestamp",
        "end_date": "timestamp",
    },
    "location": {"location_id": "int64", "region_concept_id": "int64"},
    # Minimal vocab tables for compile_codesets + Circe SQL against DuckDB.
    "concept": {
        "concept_id": "int64",
        "invalid_reason": "string",
    },
    "concept_ancestor": {
        "ancestor_concept_id": "int64",
        "descendant_concept_id": "int64",
    },
    "concept_relationship": {
        "concept_id_1": "int64",
        "concept_id_2": "int64",
        "relationship_id": "string",
        "invalid_reason": "string",
    },
}

